language: python
python:
  - '2.6'
  - '2.7'
  - '3.3'
  - pypy
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install coveralls
script:
  make coverage
notifications:
  email:
    - kimmobrunfeldt+egtest@gmail.com
after_success:
  - coveralls --verbose

